version: "3.8"
services:
  aluguel:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=192.168.0.106:0.0
    command: npm start
    volumes:
      - "/app/node_modules"
      - "./:/app"
